---
version: "3"

services:

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 3000:3000/tcp
    volumes:
      - /home/pi/adguard/work:/opt/adguardhome/work
      - /home/raspberry-pi/adguardhome:/opt/adguardhome/conf
    restart: unless-stopped

  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:stable
    container_name: homeassistant
    ports:
      - 8123:8123
    volumes:
      - /home/pi/raspberry-pi/homeassistant:/config
    environment:
      - TZ=${TZ}
    restart: always

  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true
    ports:
      - 9117:9117
    restart: unless-stopped
    volumes:
      - /home/pi/jackett/config:/config
      - downloads:/downloads

  plex:
    build:
      context: ./pms-docker
      dockerfile: Dockerfile.armv7
    container_name: plex
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://${STATIC_IP}:32400/
    volumes:
      - /home/pi/raspberry-pi/plex/config:/config
      - media:/data

  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - /home/pi/transmission/config:/config
      - downloads:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 7878:7878
    restart: unless-stopped
    volumes:
      - /home/pi/radarr/config:/config
      - media:/movies
      - downloads:/downloads

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    ports:
      - 8989:8989
    restart: unless-stopped
    volumes:
      - /home/pi/sonarr/config:/config
      - media:/tv
      - downloads:/downloads

  # caddy:
  #   build:
  #     context: .
  #     dockerfile: caddy.Dockerfile
  #   container_name: caddy
  #   ports:
  #     - 80:80 # for HTTP -> HTTPS redirect
  #     - 443:443
  #   restart: unless-stopped
  #   volumes:
  #     - /home/pi/Caddyfile:/etc/caddy/Caddyfile
  #     - /home/pi/caddy/config:/config
  #     - /home/pi/caddy/data:/data
  #   depends_on:
  #     - adguardhome

volumes:
  media:
    driver_opts:
      type: cifs
      device: //${NAS_IP}/media
      o: "addr=${NAS_IP},username=${NAS_USERNAME},password=${NAS_PASSWORD},file_mode=0777,dir_mode=0777"
  downloads:
    driver_opts:
      type: cifs
      device: //${NAS_IP}/downloads
      o: "addr=${NAS_IP},username=${NAS_USERNAME},password=${NAS_PASSWORD},file_mode=0777,dir_mode=0777"
