---
- name: Raspberry Pi playbook
  hosts: all

  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: dist
        update_cache: true

    - name: Install and set up docker and docker-compose
      include_role:
        name: nickjj.docker
        apply: 
          become: true
      tags:
        - docker

    - name: Install tmux
      become: true
      apt:
        name: tmux
        state: present

    # Set static IP
    - name: Install network manager
      become: true
      apt:
        name: network-manager
        state: present

    - name: Configure network
      become: true
      community.general.nmcli:
        state: present
        conn_name: eth0
        ifname: eth0
        type: ethernet
        ip4: 192.168.1.250/24
        gw4: 192.168.1.1
        dns4:
          - 1.1.1.1

    - name: Setup SSH authorization
      authorized_key:
        user: pi
        state: present
        key: https://github.com/martinbjeldbak.keys

    - name: Change pi user password
      become: true
      user:
        name: pi
        update_password: always
        password: "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='SSH', field='password') | password_hash('sha512') }}"

    - name: Ensure deploy key is present
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_github"
        type: ed25519
      register: deploy_key

    - name: Ensure deploy key is authorized with repository
      community.general.github_deploy_key:
        key: "{{  deploy_key.public_key }}"
        name: Raspberry Pi
        state: present
        owner: martinbjeldbak
        repo: raspberry-pi
        token: "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='GitHub', field='token') }}"

    - name: Clone GitHub repository
      git:
        repo: git@github.com:martinbjeldbak/raspberry-pi.git
        dest: /home/pi/raspberry-pi/
        clone: true
        update: true
        key_file: ~/.ssh/id_github
        accept_hostkey: true

    - name: Copy .env file (this is gitignored in cloned repo)
      ansible.builtin.copy:
        src: .env
        dest: /home/pi/raspberry-pi/.env

    - name: Create Home Assistant secrets file
      ansible.builtin.copy:
        dest: /home/pi/raspberry-pi/homeassistant/secrets.yaml
        content: |
          ---
          latitude: {{ "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='Home Assistant', field='Latitude') | password_hash('sha512') }}" }}
          longitude: {{ "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='Home Assistant', field='Longitude') | password_hash('sha512') }}" }}
          spotifyclientid: {{ "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='Home Assistant', field='Spotify Client ID') | password_hash('sha512') }}" }}
          spotifyclientsecret: {{ "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='Home Assistant', field='Spotify Client Secret') | password_hash('sha512') }}" }}
          routerpassword: {{ "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='Home Assistant', field='Router Password') | password_hash('sha512') }}" }}
          radarr_api_key: {{ "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='Home Assistant', field='Radarr API Key') | password_hash('sha512') }}" }}

    - name: Install unattended upgrades
      become: true
      apt:
        name: unattended-upgrades
        state: present

    - name: Setup unattended upgrades
      debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        vtype: boolean
        value: "true"

    - name: Install fail2ban # prevent SSH bruteforcing
      become: true
      apt:
        name: fail2ban
        state: present

    - name: Install ufw
      become: true
      apt:
        name: ufw
        state: present

    - name: Limit ssh
      become: true
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp

    - name: Allow access to required ports
      become: true
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
      loop:
        - SSH
        - DNS
        - WWW
        - WWW Secure
        - '9117' # Jackett
        - '32400' # Plex
        - '9091' # Transmission UI
        - '51413' # Transmission
        - '7878' # Radarr
        - '8989' # Sonarr

    - name: Enable ufw and default to deny
      become: true
      ufw:
        state: enabled
        default: deny

    - name: Create and start docker-compose services
      community.docker.docker_compose:
        project_src: /home/pi/raspberry-pi
        pull: true
        build: true
        remove_orphans: true
      register: output
      tags:
        - docker



