---
- name: Raspberry Pi playbook
  hosts: all

  tasks:
    - name: Increase swap size
      include_role:
        name: geerlingguy.swap
        apply:
          become: true
      vars:
        swap_file_size_mb: '2048'

    - name: Set timezone to Melbourne
      become: true
      community.general.timezone:
        name: Australia/Melbourne

    - name: Restart crond to pick up timezone change
      become: true
      ansible.builtin.service:
        name: cron
        state: restarted

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: dist
        update_cache: true

    # See https://askubuntu.com/a/1264921/431204
    - name: Download updated libseccomp for Plex support
      become: true
      apt:
        deb: http://ftp.au.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
      tags:
        - docker

    - name: Install and set up docker and docker-compose
      include_role:
        name: nickjj.docker
        apply:
          become: true
      tags:
        - docker

    - name: Install tmux
      become: true
      apt:
        name: tmux
        state: present

    - name: Install vim
      become: true
      apt:
        name: vim
        state: present

    # Set static IP
    - name: Install network manager
      become: true
      apt:
        name: network-manager
        state: present

    - name: Configure network
      become: true
      community.general.nmcli:
        state: present
        conn_name: eth0
        ifname: eth0
        type: ethernet
        ip4: 192.168.1.250/24
        gw4: 192.168.1.1
        dns4:
          - 1.1.1.1

    - name: Setup SSH authorization
      authorized_key:
        user: pi
        state: present
        key: https://github.com/martinbjeldbak.keys

    - name: Change pi user password
      become: true
      user:
        name: pi
        update_password: always
        password: "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='SSH', field='password') | password_hash('sha512') }}"

    - name: Ensure deploy key is present
      community.crypto.openssh_keypair:
        path: "~/.ssh/id_github"
        type: ed25519
      register: deploy_key

    - name: Ensure deploy key is authorized with repository
      community.general.github_deploy_key:
        key: "{{  deploy_key.public_key }}"
        name: Raspberry Pi
        state: present
        owner: martinbjeldbak
        repo: raspberry-pi
        token: "{{ lookup('community.general.onepassword', 'Raspberry Pi', section='GitHub', field='token') }}"

    - name: Clone GitHub repository
      git:
        repo: git@github.com:martinbjeldbak/raspberry-pi.git
        dest: /home/pi/raspberry-pi/
        clone: true
        depth: 1
        update: true
        recursive: true
        key_file: ~/.ssh/id_github
        accept_hostkey: true
      tags:
        - docker # reflect changes in docker-compose.yml
        - caddy

    - name: Set Adguard Configuration file
      ansible.builtin.template:
        src: adguardhome/AdGuardHome.tpl.yaml
        dest: /home/pi/raspberry-pi/adguardhome/AdGuardHome.yaml
      tags:
        - adguard

    - name: Set Jackett configuration file
      ansible.builtin.template:
        src: jackett/config/Jackett/ServerConfig.tpl.json
        dest: /home/pi/raspberry-pi/jackett/config/Jackett/ServerConfig.json
      tags:
        - jackett

    - name: Create docker-compose .env file
      ansible.builtin.copy:
        dest: /home/pi/raspberry-pi/.env
        content: |
          TZ=Australia/Melbourne
          STATIC_IP=raspberrypi.local
          PLEX_CLAIM={{ lookup('community.general.onepassword', 'Raspberry Pi', section='Plex', field='Claim') }}
          NAS_IP={{ lookup('community.general.onepassword', 'Raspberry Pi', section='NAS', field='IP') }}
          NAS_USERNAME={{ lookup('community.general.onepassword', 'Raspberry Pi', section='NAS', field='Username') }}
          NAS_PASSWORD={{ lookup('community.general.onepassword', 'Raspberry Pi', section='NAS', field='Password') }}
          TRANSMISSION_USERNAME={{ lookup('community.general.onepassword', 'Raspberry Pi', section='Transmission', field='Username') }}
          TRANSMISSION_PASSWORD={{ lookup('community.general.onepassword', 'Raspberry Pi', section='Transmission', field='Password') }}
      tags:
        - credentials

    - name: Create Home Assistant secrets.yaml
      ansible.builtin.template:
        src: homeassistant/secrets.tpl.yaml
        dest: /home/pi/raspberry-pi/homeassistant/secrets.yaml
      tags:
        - credentials

    - name: Set Caddy secret
      ansible.builtin.copy:
        dest: /home/pi/raspberry-pi/.caddy.env
        content: |
          CLOUDFLARE_API_TOKEN={{ lookup('community.general.onepassword', 'Raspberry Pi', section='Caddy', field='Cloudflare Token') }}
      tags:
        - caddy

    - name: Install unattended upgrades
      become: true
      apt:
        name: unattended-upgrades
        state: present

    - name: Setup unattended upgrades
      debconf:
        name: unattended-upgrades
        question: unattended-upgrades/enable_auto_updates
        vtype: boolean
        value: "true"

    - name: Install fail2ban
      become: true
      apt:
        name: fail2ban
        state: present

    - name: Install ufw
      become: true
      apt:
        name: ufw
        state: present
      tags:
        - firewall

    - name: Limit ssh # connection reate limiting
      become: true
      community.general.ufw:
        rule: limit
        port: ssh
        proto: tcp
      tags:
        - firewall

    - name: Allow access to required ports
      become: true
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
      loop:
        - ssh
        - https
        - '53' # Adguard Home DNS
        - '32469' # Plex
        - '32410' # Plex
        - '32412' # Plex
        - '32413' # Plex
        - '32414' # Plex
        - '51413' # Transmission
      tags:
        - firewall

    - name: Enable ufw and default to deny
      become: true
      ufw:
        state: enabled
        default: deny
      tags:
        - firewall

    - name: Setup backup task to backup every day at 5am
      ansible.builtin.cron:
        name: "Backup to NAS"
        minute: "0"
        hour: "5"
        job: "rsync -av --progress /home/pi {{ lookup('community.general.onepassword', 'Raspberry Pi', section='NAS', field='Username') }}@{{ lookup('community.general.onepassword', 'Raspberry Pi', section='NAS', field='IP') }}:/volume1/NetBackup/raspberry-pi-backups" # noqa 204
      tags:
        - backup

    - name: Setup logrotate
      become: true
      blockinfile:
        path: "/etc/logrotate.d/{{ item.path }}"
        block: "{{ item.conf }}"
        create: true
        mode: '644'
      loop:
        - path: adguardhome-logs
          conf: |
            /home/pi/adguardhome/work/adguardhome-*.log {
              weekly
              rotate 3
              size 10M
              compress
              delaycompress
            }
        - path: adguardhome-query-logs
          conf: |
            /home/pi/adguardhome/work/data/querylog.json {
              weekly
              rotate 3
              size 10M
              compress
              delaycompress
            }
      tags:
        - logrotate

    - name: Create and start docker-compose services
      become: true
      community.docker.docker_compose:
        project_src: /home/pi/raspberry-pi
        pull: true
        build: true
        remove_orphans: true
      vars:
        ansible_python_interpreter: "/usr/bin/env python3-docker"
      register: output
      tags:
        - docker
        - credentials
        - caddy
