- id: '1687322185169'
  alias: Turn off air purifier
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - type: turn_off
    device_id: a974d5ae993c3a8ac8fe4b666c2ff223
    entity_id: fan.mi_air_purifier_3h
    domain: fan
  mode: single
- id: '1687322354221'
  alias: Turn on Air Purifier
  description: Before bed
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.martin_madsen
      zone: zone.home
    - condition: zone
      entity_id: person.nandar
      zone: zone.home
  action:
  - type: turn_on
    device_id: a974d5ae993c3a8ac8fe4b666c2ff223
    entity_id: fan.mi_air_purifier_3h
    domain: fan
  mode: single
- id: '1687613174907'
  alias: Plex off lights when watching tv at night
  description: ''
  trigger:
  - platform: device
    device_id: f196d9f15d0b393d82a9b7945b6cc269
    domain: media_player
    entity_id: e1137ef10ecb8f6ba5e2d71968e84f8d
    type: playing
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
  - service: light.turn_off
    data:
      transition: 10
    target:
      area_id: living_room
  mode: single
- id: '1687613224875'
  alias: Plex Movie paused at night
  description: ''
  trigger:
  - platform: device
    device_id: f196d9f15d0b393d82a9b7945b6cc269
    domain: media_player
    entity_id: e1137ef10ecb8f6ba5e2d71968e84f8d
    type: paused
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_movie_paused
    metadata: {}
  mode: single
- id: '1694783062795'
  alias: Hue Dimmer Nandar Laptop WOL
  description: WOL integration to turn on Nandar's laptop via Hue Dimmer switch
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_2
    attribute: event_type
    to: long_release
  condition: []
  action:
  - parallel:
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.nandar_work_laptop
    - service: switch.turn_on
      data: {}
      target:
        entity_id: switch.nandar_work_laptop_wifi
  mode: single
- id: '1694784402214'
  alias: Hue Dimmer Turn on living room
  description: Living room lights
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_1
    attribute: event_type
    to: short_release
  condition: []
  action:
  - parallel:
    - service: adaptive_lighting.apply
      data:
        adapt_color: true
        adapt_brightness: true
        turn_on_lights: true
        entity_id: switch.adaptive_lighting_living_room
    - service: climate.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: climate.living_room_ac
  - if:
    - condition: numeric_state
      entity_id: sensor.living_room_broadlink_temperature
      above: 24
    then:
    - service: climate.set_hvac_mode
      target: {}
      data:
        hvac_mode: cool
    else:
    - service: climate.set_hvac_mode
      target:
        entity_id:
        - climate.living_room_ac
      data:
        hvac_mode: dry
  - service: climate.set_fan_mode
    metadata: {}
    data:
      fan_mode: highest
    target:
      entity_id: climate.living_room_ac
  mode: single
- id: '1694784530273'
  alias: Hue Dimmer turn off living room
  description: Living room lights
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_4
  condition: []
  action:
  - parallel:
    - service: light.turn_off
      data: {}
      target:
        area_id: living_room
    - service: climate.turn_off
      metadata: {}
      data: {}
      target:
        entity_id: climate.living_room_ac
  mode: single
- id: '1694785112288'
  alias: 'Adaptive lighting: reset manual_control after 1 hour'
  description: 'Source: https://github.com/basnijholt/adaptive-lighting/tree/5cd060a37c2cdad3c7e266b937dc50e4b1c79711#robot-automation-examples'
  trigger:
    platform: event
    event_type: adaptive_lighting.manual_control
  action:
  - delay: 01:00:00
  - condition: template
    value_template: '{{ light in state_attr(switch, ''manual_control'') }}'
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: '{{ switch }}'
      lights: '{{ light }}'
      manual_control: false
  mode: parallel
  variables:
    light: '{{ trigger.event.data.entity_id }}'
    switch: '{{ trigger.event.data.switch }}'
- id: '1694785300713'
  alias: 'Hue Dimmer: Increase brightness'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_2
    attribute: event_type
    to: short_release
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: 20
    target:
      area_id: living_room
  - service: adaptive_lighting.set_manual_control
    data:
      manual_control: true
      entity_id: switch.adaptive_lighting_living_room
  mode: single
- id: '1694785348532'
  alias: 'Hue Dimmer: Decrease brightness'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_3
    attribute: event_type
    from: short_release
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: -20
    target:
      area_id: living_room
  - service: adaptive_lighting.set_manual_control
    data:
      manual_control: true
      entity_id: switch.adaptive_lighting_living_room
  mode: single
- id: '1704424867342'
  alias: Aranet low battery notification
  description: Notify on low battery
  trigger:
  - type: battery_level
    platform: device
    device_id: 4d9c607685d2fb9bf51b4c55ab3c1a50
    entity_id: 8cbb96637c2ea92e52ad0b387bf1c7b6
    domain: sensor
    below: 10
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_dagobah
    metadata: {}
    data:
      message: Aranet battery is below 10%
      title: Aranet battery low
  mode: single
- id: '1709210255854'
  alias: Longfan Oscilate after turn on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.longfan
  condition: []
  action:
  - service: script.longfan_oscillate
    metadata: {}
    data: {}
  mode: single
