- id: '1687322185169'
  alias: Turn off air purifier
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - type: turn_off
    device_id: a974d5ae993c3a8ac8fe4b666c2ff223
    entity_id: fan.mi_air_purifier_3h
    domain: fan
  mode: single
- id: '1687322354221'
  alias: Turn on Air Purifier
  description: Before bed
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.martin_madsen
      zone: zone.home
    - condition: zone
      entity_id: person.nandar
      zone: zone.home
  action:
  - type: turn_on
    device_id: a974d5ae993c3a8ac8fe4b666c2ff223
    entity_id: fan.mi_air_purifier_3h
    domain: fan
  mode: single
- id: '1687613174907'
  alias: Plex off lights when watching tv at night
  description: ''
  trigger:
  - platform: device
    device_id: f196d9f15d0b393d82a9b7945b6cc269
    domain: media_player
    entity_id: e1137ef10ecb8f6ba5e2d71968e84f8d
    type: playing
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
  - service: light.turn_off
    data:
      transition: 10
    target:
      area_id: living_room
  mode: single
- id: '1687613224875'
  alias: Plex Movie paused at night
  description: ''
  trigger:
  - platform: device
    device_id: f196d9f15d0b393d82a9b7945b6cc269
    domain: media_player
    entity_id: e1137ef10ecb8f6ba5e2d71968e84f8d
    type: paused
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
  - target:
      entity_id: scene.watching_tv
    metadata: {}
    action: scene.turn_on
  mode: single
- id: '1694783062795'
  alias: Hue Dimmer Nandar Laptop WOL
  description: WOL integration to turn on Nandar's laptop via Hue Dimmer switch
  trigger:
  - platform: device
    domain: mqtt
    device_id: 04229db32395a8222ce78362a5da4c8b
    type: action
    subtype: up-hold
  condition: []
  action:
  - parallel:
    - data: {}
      target:
        entity_id: switch.nandar_work_laptop
      action: switch.turn_on
    - data: {}
      target:
        entity_id: switch.nandar_work_laptop_wifi
      action: switch.turn_on
  mode: single
- id: '1694784402214'
  alias: Hue Dimmer Turn on living room
  description: Living room lights
  trigger:
  - platform: device
    domain: mqtt
    device_id: 04229db32395a8222ce78362a5da4c8b
    type: action
    subtype: on_press
  condition: []
  action:
  - action: light.toggle
    data: {}
    target:
      area_id: living_room
  mode: single
- id: '1694784530273'
  alias: Hue Dimmer turn off living room
  description: Living room lights
  trigger:
  - platform: device
    domain: mqtt
    device_id: 04229db32395a8222ce78362a5da4c8b
    type: action
    subtype: off_press
  condition: []
  action:
  - data: {}
    target:
      area_id: living_room
    action: light.turn_off
  mode: single
- id: '1694785112288'
  alias: 'Adaptive lighting: reset manual_control after 1 hour'
  description: 'Source: https://github.com/basnijholt/adaptive-lighting/tree/5cd060a37c2cdad3c7e266b937dc50e4b1c79711#robot-automation-examples'
  trigger:
    platform: event
    event_type: adaptive_lighting.manual_control
  action:
  - delay: 01:00:00
  - condition: template
    value_template: '{{ light in state_attr(switch, ''manual_control'') }}'
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: '{{ switch }}'
      lights: '{{ light }}'
      manual_control: false
  mode: parallel
  variables:
    light: '{{ trigger.event.data.entity_id }}'
    switch: '{{ trigger.event.data.switch }}'
- id: '1694785300713'
  alias: 'Hue Dimmer: Increase brightness'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 04229db32395a8222ce78362a5da4c8b
    type: action
    subtype: up_press
  condition: []
  action:
  - data:
      manual_control: true
      entity_id: switch.adaptive_lighting_living_room
    action: adaptive_lighting.set_manual_control
    enabled: false
  - data:
      brightness_step_pct: 20
      transition: 2
    target:
      area_id: living_room
    action: light.turn_on
  mode: single
- id: '1694785348532'
  alias: 'Hue Dimmer: Decrease brightness'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 04229db32395a8222ce78362a5da4c8b
    type: action
    subtype: down_press
  condition: []
  action:
  - data:
      brightness_step_pct: -20
      transition: 2
    target:
      area_id: living_room
    action: light.turn_on
  - data:
      manual_control: true
      entity_id: switch.adaptive_lighting_living_room
    action: adaptive_lighting.set_manual_control
    enabled: false
  mode: single
- id: '1704424867342'
  alias: Aranet low battery notification
  description: Notify on low battery
  trigger:
  - type: battery_level
    platform: device
    device_id: 4d9c607685d2fb9bf51b4c55ab3c1a50
    entity_id: 8cbb96637c2ea92e52ad0b387bf1c7b6
    domain: sensor
    below: 10
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_dagobah
    metadata: {}
    data:
      message: Aranet battery is below 10%
      title: Aranet battery low
  mode: single
- id: '1709210255854'
  alias: Longfan Oscilate after turn on
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.longfan
  condition: []
  action:
  - service: script.longfan_oscillate
    metadata: {}
    data: {}
  mode: single
- id: '1724334337502'
  alias: Apply adaptive lighting
  description: Living room lights
  trigger:
  - platform: device
    domain: mqtt
    device_id: 04229db32395a8222ce78362a5da4c8b
    type: action
    subtype: on-hold
  condition: []
  action:
  - action: adaptive_lighting.apply
    metadata: {}
    data:
      adapt_color: true
      adapt_brightness: true
      turn_on_lights: true
      lights:
      - light.hue_living_room_filament_bulb
      - light.hue_living_room_light_strip
      - light.hue_living_room_white_bulb
      entity_id: switch.adaptive_lighting_living_room
  mode: single
- id: '1724497467298'
  alias: 'Bedroom Dimmer: Turn on'
  description: Beroom lights
  trigger:
  - platform: device
    domain: mqtt
    device_id: 11fe4eb3d9903045257bbbed8af16b4a
    type: action
    subtype: on_press
  condition: []
  action:
  - if:
    - condition: time
      after: '21:00:00'
    then:
    - action: switch.turn_on
      metadata: {}
      data: {}
      target:
        entity_id: switch.adaptive_lighting_sleep_mode_bedroom
    enabled: false
  - action: light.toggle
    target:
      entity_id:
      - light.bedroom_lights
    data: {}
  mode: single
- id: '1724497757357'
  alias: 'Hue Dimmer: Turn off bedroom lights'
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 11fe4eb3d9903045257bbbed8af16b4a
    type: action
    subtype: off_press
  condition: []
  action:
  - data: {}
    action: light.turn_off
    target:
      entity_id: light.bedroom_lights
  mode: single
- id: '1724497874059'
  alias: Bedroom turn down brightness
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 11fe4eb3d9903045257bbbed8af16b4a
    type: action
    subtype: down_press
  condition: []
  action:
  - data:
      brightness_step_pct: -20
      transition: 2
    target:
      area_id: living_room
    action: light.turn_on
  - data:
      manual_control: true
      entity_id: switch.adaptive_lighting_bedroom
    action: adaptive_lighting.set_manual_control
  mode: single
- id: '1724497930665'
  alias: Bedroom increase brightness
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 11fe4eb3d9903045257bbbed8af16b4a
    type: action
    subtype: up_press
  condition: []
  action:
  - data:
      manual_control: true
      entity_id: switch.adaptive_lighting_bedroom
    action: adaptive_lighting.set_manual_control
  - data:
      brightness_step_pct: 20
      transition: 2
    action: light.turn_on
    target:
      area_id: bedroom
  mode: single
- id: '1724629229771'
  alias: Turn off sleep mode when sun rises
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.adaptive_lighting_sleep_mode_bedroom
  mode: single
- id: '1724677054506'
  alias: Apply adaptive-lighting Bedroom
  description: Bedroom room lights
  trigger:
  - platform: device
    domain: mqtt
    device_id: 11fe4eb3d9903045257bbbed8af16b4a
    type: action
    subtype: on_hold
  condition: []
  action:
  - action: adaptive_lighting.apply
    metadata: {}
    data:
      adapt_color: true
      adapt_brightness: true
      turn_on_lights: true
      lights:
      - light.hue_bedroom_light_strip
      - light.hue_martin_side
      - light.hue_nandar_side_lamp
      entity_id: switch.adaptive_lighting_bedroom
  mode: single
- id: '1727478901057'
  alias: Backup configuration
  description: ''
  trigger:
  - platform: time
    at: 01:00:00
  condition: []
  action:
  - action: backup.create
    metadata: {}
    data: {}
  mode: single
- id: '1727673306499'
  alias: Adguard Home re-enable protection
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 01e54bbfb54d47bf1c8fd90f8c19b1aa
    entity_id: 87e151a8d51720b2ace6a8e9cc5b56e1
    domain: switch
  condition: []
  action:
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_on
    device_id: 01e54bbfb54d47bf1c8fd90f8c19b1aa
    entity_id: 87e151a8d51720b2ace6a8e9cc5b56e1
    domain: switch
  mode: single
- id: '1727673671554'
  alias: AdGuard Protection On
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 01e54bbfb54d47bf1c8fd90f8c19b1aa
    entity_id: 87e151a8d51720b2ace6a8e9cc5b56e1
    domain: switch
  condition: []
  action:
  - type: turn_on
    device_id: ca4923919fa9ac181bc629a20ad6b7b0
    entity_id: 1d947504c00931fd8b19e2ae28c28b66
    domain: switch
  mode: single
- id: '1727673692327'
  alias: AdGuard Protection Off
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 01e54bbfb54d47bf1c8fd90f8c19b1aa
    entity_id: 87e151a8d51720b2ace6a8e9cc5b56e1
    domain: switch
  condition: []
  action:
  - type: turn_off
    device_id: ca4923919fa9ac181bc629a20ad6b7b0
    entity_id: 1d947504c00931fd8b19e2ae28c28b66
    domain: switch
  mode: single
- id: '1728990137117'
  alias: Outside water flowing notification
  description: To catch any leaks
  triggers:
  - type: value
    device_id: fb1b4a5297db45ef6fb5f7f910ae8c83
    entity_id: e6dcbc82e9d4165a7b511a0e8fbcf3c6
    domain: sensor
    trigger: device
    above: 0
  conditions: []
  actions:
  - action: notify.martin_s_devices
    metadata: {}
    data:
      title: Water flowing in valve
      message: Valve was turned on and is flowing
  mode: single
- id: '1729301727323'
  alias: Turn off water valve automatically
  description: To make sure we don't accidentally leave it open and cause leaks
  triggers:
  - type: turned_on
    device_id: fb1b4a5297db45ef6fb5f7f910ae8c83
    entity_id: ea62c05b6e5050ddfe2adf567499a31b
    domain: switch
    trigger: device
    for:
      hours: 0
      minutes: 30
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: fb1b4a5297db45ef6fb5f7f910ae8c83
    entity_id: ea62c05b6e5050ddfe2adf567499a31b
    domain: switch
  mode: single
- id: '1729319892883'
  alias: Turn on Air Purifier when someone in office
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - device_tracker.nandar_gigabyte_laptop
    - device_tracker.nandar_s_gigabyte_laptop
    to: home
  conditions: []
  actions:
  - type: turn_on
    device_id: a974d5ae993c3a8ac8fe4b666c2ff223
    entity_id: a46393b355794e72b229815d644cf743
    domain: fan
  mode: single
- id: '1729426288351'
  alias: Restart zigbee2mqtt
  description: Otherwise it seems to randomly bug out
  triggers:
  - trigger: time
    at: 00:00:00
  conditions: []
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.docker_zigbee2mqtt
  - delay:
      hours: 0
      minutes: 0
      seconds: 30
      milliseconds: 0
  - action: switch.turn_on
    target:
      entity_id:
      - switch.docker_zigbee2mqtt
    data: {}
  mode: single
