- id: '1687322185169'
  alias: Turn off air purifier
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - type: turn_off
    device_id: a974d5ae993c3a8ac8fe4b666c2ff223
    entity_id: fan.mi_air_purifier_3h
    domain: fan
  mode: single
- id: '1687322354221'
  alias: Turn on Air Purifier
  description: Before bed
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: device
    device_id: 3689b8cb31ba6f23d3de3ea764896d00
    domain: device_tracker
    entity_id: f44d19bd56b5aa74f707ce10d390926f
    type: is_home
  action:
  - type: turn_on
    device_id: a974d5ae993c3a8ac8fe4b666c2ff223
    entity_id: fan.mi_air_purifier_3h
    domain: fan
  mode: single
- id: '1687613174907'
  alias: Plex off lights when watching tv at night
  description: ''
  trigger:
  - platform: device
    device_id: ac2cebc503b95c6c65837616b96292dc
    domain: media_player
    entity_id: media_player.plex_plex_for_apple_tv_apple_tv
    type: playing
  condition:
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
  - service: light.turn_off
    data:
      transition: 10
    target:
      area_id: living_room
  mode: single
- id: '1687613224875'
  alias: Plex Movie paused at night
  description: ''
  trigger:
  - platform: device
    device_id: ac2cebc503b95c6c65837616b96292dc
    domain: media_player
    entity_id: media_player.plex_plex_for_apple_tv_apple_tv
    type: paused
  condition:
  - condition: time
    after: '17:00:00'
  - condition: sun
    after: sunset
    after_offset: -01:00:00
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.living_room_movie_paused
    metadata: {}
  mode: single
- id: '1694783062795'
  alias: Hue Dimmer Nandar Laptop WOL
  description: WOL integration to turn on Nandar's laptop via Hue Dimmer switch
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_2
    attribute: event_type
    to: long_release
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.nandar_work_laptop
  mode: single
- id: '1694784402214'
  alias: Hue Dimmer Turn on living room
  description: Living room lights
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_1
    attribute: event_type
    to: short_release
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.living_room_lights
  - service: adaptive_lighting.apply
    data:
      entity_id: switch.adaptive_lighting_adapt_brightness_default
      lights:
      - light.living_room_lights
      adapt_color: true
      adapt_brightness: true
      turn_on_lights: true
  mode: single
- id: '1694784530273'
  alias: Hue Dimmer turn off living room
  description: Living room lights
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_4
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.living_room_lights
  mode: single
- id: '1694785112288'
  alias: 'Adaptive lighting: reset manual_control after 1 hour'
  description: 'Source: https://github.com/basnijholt/adaptive-lighting/tree/5cd060a37c2cdad3c7e266b937dc50e4b1c79711#robot-automation-examples'
  trigger:
  - platform: event
    event_type: adaptive_lighting.manual_control
  action:
  - delay: 01:00:00
  - condition: template
    value_template: '{{ light in state_attr(switch, ''manual_control'') }}'
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: '{{ switch }}'
      lights: '{{ light }}'
      manual_control: false
  mode: parallel
  variables:
    light: '{{ trigger.event.data.entity_id }}'
    switch: '{{ trigger.event.data.switch }}'
- id: '1694785300713'
  alias: 'Hue Dimmer: Increase brightness'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_2
    attribute: event_type
    to: short_release
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: 20
    target:
      entity_id: light.living_room_lights
  mode: single
- id: '1694785348532'
  alias: 'Hue Dimmer: Decrease brightness'
  description: ''
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_3
    attribute: event_type
    from: short_release
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_step_pct: -20
    target:
      entity_id: light.living_room_lights
  mode: single
- id: '1694785593921'
  alias: 'Hue Dimmer: Apply adaptive lightning'
  description: Long press on on button
  trigger:
  - platform: state
    entity_id:
    - event.hue_dimmer_switch_button_1
    attribute: event_type
    to: long_release
  condition: []
  action:
  - service: adaptive_lighting.apply
    data:
      entity_id: switch.adaptive_lighting_adapt_brightness_default
      lights:
      - light.living_room_lights
      adapt_color: true
      adapt_brightness: true
      turn_on_lights: true
  mode: single
- id: '1698202098549'
  alias: Frigate Notifications (0.12.0.1)
  description: ''
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.eufy_indoor_pan_tilt
      notify_device: 3689b8cb31ba6f23d3de3ea764896d00
      base_url: https://homeassistant.local.martinbjeldbak.com
      title: Living Room Camera notification
      update_thumbnail: true
      ios_live_view: true
      tv_transparency: 0%
      tv: false
- id: '1698202385595'
  alias: Camera Upstairs camera notification
  description: 'Source: https://docs.frigate.video/guides/ha_notifications/'
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.eufy_indoor_pan_tilt
      notify_device: 3689b8cb31ba6f23d3de3ea764896d00
      base_url: https://homeassistant.local.martinbjeldbak.com
      title: Someone detected on upstairs camera
      update_thumbnail: true
      ios_live_view: false
- id: '1698288161573'
  alias: Camera middle
  description: 'Source: https://docs.frigate.video/guides/ha_notifications/'
  use_blueprint:
    path: SgtBatten/Stable.yaml
    input:
      camera: camera.eufy_indoor_2k
      notify_device: 3689b8cb31ba6f23d3de3ea764896d00
      base_url: https://homeassistant.local.martinbjeldbak.com
      title: Someone detected on middle camera
      update_thumbnail: true
      ios_live_view: false
- id: '1704424503348'
  alias: Notify on high CO2 levels
  description: ''
  trigger:
  - type: carbon_dioxide
    platform: device
    device_id: 4d9c607685d2fb9bf51b4c55ab3c1a50
    entity_id: ed0a51483b5d909800a6c5140ea41d2a
    domain: sensor
    above: 1000
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_dagobah
    metadata: {}
    data:
      message: CO2 levels are high at {{states("sensor.aranet4_20b7d_carbon_dioxide")
        }} ppm
      title: CO2 Levels High
  - service: notify.email_using_fastmail
    metadata: {}
    data:
      message: CO2 levels are high at {{states("sensor.aranet4_20b7d_carbon_dioxide")
        }}ppm. See details here:<a href="https://homeassistant.local.martinbjeldbak.com/history?entity_id=sensor.aranet4_20b7d_carbon_dioxide">here</a>
      title: CO2 levels high
  mode: single
- id: '1704424867342'
  alias: Aranet low battery notification
  description: Notify on low battery
  trigger:
  - type: battery_level
    platform: device
    device_id: 4d9c607685d2fb9bf51b4c55ab3c1a50
    entity_id: 8cbb96637c2ea92e52ad0b387bf1c7b6
    domain: sensor
    below: 10
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_dagobah
    metadata: {}
    data:
      message: Aranet battery is below 10%
      title: Aranet battery low
  mode: single
