---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  trusted_proxies:
    - 172.20.0.0/24
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

#   url: https://192.168.1.1/api
#   api_key: !secret opnsense_user
#   api_secret: !secret opnsense_key
#   verify_ssl: false
#   tracker_interfaces:
#     - USER

notify:
  - name: "Email using Fastmail"
    platform: smtp
    sender: homeassistant@martinbjeldbak.com
    recipient: me@martinbjeldbak.com
    server: !secret smtp_server
    port: 465 # SSL
    username: !secret smtp_username
    password: !secret smtp_password
    encryption: tls
    sender_name: Martin's Home Assistant

sensor:
   - platform: epsonworkforce
     host: 192.168.30.17
     monitored_conditions:
     - black
     - photoblack
     - yellow
     - magenta
     - cyan
     - clean

rest_command:
  wake_nandar_work_laptop:
      url: 'https://192.168.1.1/api/wol/wol/set'
      verify_ssl: false
      method: POST
      payload: '{"wake":{"interface": "opt3","mac": "80:fa:5b:90:f0:fd"}}'
      content_type:  'application/json'
      username: !secret opnsense_user
      password: !secret opnsense_key

switch:
  - platform: template
    switches:
      nandar_work_laptop:
        unique_id: nandar_work_laptop
        friendly_name: "Nandar's Work Laptop"
        value_template: "{{ is_state('binary_sensor.nandar_s_work_laptop', 'on') }}"
        turn_on:
          service: rest_command.wake_nandar_work_laptop
        turn_off: # Added as required, no way to wake-off-lan without running script
        icon_template: >-
          {% if is_state('binary_sensor.nandar_s_work_laptop', 'on') %}
            mdi:laptop
          {% else %}
            mdi:laptop-off
          {% endif %}

homeassistant:
  name: Home
  unit_system: metric
  time_zone: !secret tz
  latitude: !secret latitude
  longitude: !secret longitude
  currency: AUD
  internal_url: !secret external_url
  external_url: !secret external_url

logger:
  default: info

homekit:
  advertise_ip: "192.168.10.16"
  filter:
    include_domains:
      - sensor
      - fan
      - climate
    include_entities:
      - switch.string_lights
  entity_config:
    fan.mi_air_purifier_3h:
      name: Air Purifier

binary_sensor:
  - platform: ping
    host: 192.168.20.15
    name: "Nandar's Work Laptop"
    count: 2
    scan_interval: 30

adaptive_lighting:
  min_brightness: 5
  lights:
    - light.living_room_lights

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

smartir:
climate:
  - platform: smartir
    name: Living room AC
    unique_id: living_room_ac
    device_code: 1135 # source: https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#available-codes-for-climate-devices
    controller_data: remote.living_room_broadlink
    temperature_sensor: sensor.living_room_broadlink_temperature
    humidity_sensor: sensor.living_room_broadlink_humidity
