---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  trusted_proxies:
    - 172.20.0.0/24
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

wake_on_lan:

opnsense:
  url: !secret opnsense_api_url
  api_key: !secret opnsense_key
  api_secret: !secret opnsense_secret
  
switch:
  - platform: wake_on_lan
    name: !secret n_work_laptop
    mac: !secret n_work_laptop_mac

homeassistant:
  name: Home
  unit_system: metric
  time_zone: !secret tz
  latitude: !secret latitude
  longitude: !secret longitude
  currency: AUD
  internal_url: !secret external_url
  external_url: !secret external_url

logger:
  default: info

homekit:
  filter:
    include_domains:
      - sensor
      - fan
    include_entities:
      - switch.string_lights
  entity_config:
    fan.mi_air_purifier_3h:
      name: Air Purifier

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_15m

adaptive_lighting:
  lights:
    - light.living_room_floorlamp
    - light.martin_desk_lightstrip
    - light.tv_lightstrip

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
