---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

http:
  trusted_proxies:
    - 172.20.0.0/24
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5


homeassistant:
  name: Home
  unit_system: metric
  time_zone: !secret tz
  latitude: !secret latitude
  longitude: !secret longitude
  currency: AUD
  internal_url: !secret external_url
  external_url: !secret external_url

light:
  - platform: group
    name: Living Room
    entities:
      - light.living_room
      - light.hue_lightstrip

logger:
  default: info

homekit:
  advertise_ip: "192.168.1.250"

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_free
      - type: load_1m
      - type: load_15m

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
