---
- Media:
    - Plex:
        icon: plex.svg
        href: "https://plex.local.martinbjeldbak.com"
        description: media server
        server: localdocker
        container: plex
        widget:
          type: plex
          url: http://plex:32400
          key: {{HOMEPAGE_VAR_PLEX_TOKEN}}
    - Tautulli:
        icon: tautulli.svg
        href: "https://tautulli.local.martinbjeldbak.com"
        description: plex monitoring and history database
        server: localdocker
        container: tautulli
        widget:
          type: tautulli
          url: http://tautulli:8181
          key: {{HOMEPAGE_VAR_TAUTULLI_API_KEY}}
    - Sonarr:
        icon: sonarr.svg
        description: tv
        href: "https://tv.local.martinbjeldbak.com"
        server: localdocker
        container: sonarr
        widget:
          type: sonarr
          url: http://sonarr:8989
          key: {{HOMEPAGE_VAR_SONARR_API_KEY}}
    - Bazarr:
        icon: bazarr.svg
        description: subtitles
        href: "https://subtitles.local.martinbjeldbak.com"
        server: localdocker
        container: bazarr
        widget:
          type: bazarr
          url: http://bazarr:6767
          key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}
    - Synology:
        icon: synology.svg
        description: diskstation
        ping: 192.168.10.10
        href: "https://nas.local.martinbjeldbak.com"
        widget:
            type: diskstation
            url: http://192.168.10.10:5000
            username: {{HOMEPAGE_VAR_SYNOLOGY_STATS_USERNAME}}
            password: {{HOMEPAGE_VAR_SYNOLOGY_STATS_PASSWORD}}
            volume: volume_3
    - Overseerr:
        icon: overseerr.svg
        description: plex media requests
        href: "https://request.local.martinbjeldbak.com"
        server: localdocker
        container: overseerr
        widget:
            type: overseerr
            url: http://overseerr:5055
            key: {{HOMEPAGE_VAR_OVERSEERR_API_KEY}}
    - Prowlarr:
        icon: prowlarr.svg
        description: indexer
        href: "https://prowlarr.local.martinbjeldbak.com"
        server: localdocker
        container: prowlarr
        widget:
            type: prowlarr
            url: http://gluetun:9696
            key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}
    - Radarr:
        icon: radarr.svg
        description: movies
        href: "https://movies.local.martinbjeldbak.com"
        server: localdocker
        container: radarr
        widget:
            type: radarr
            url: http://radarr:7878
            key: {{HOMEPAGE_VAR_RADARR_API_KEY}}
    - Transmission:
        icon: transmission.svg
        description: torrents
        href: "https://torrents.local.martinbjeldbak.com"
        server: localdocker
        container: transmission
        widget:
            type: transmission
            url: http://gluetun:9091
            username: {{HOMEPAGE_VAR_TRANSMISSION_USERNAME}}
            password: {{HOMEPAGE_VAR_TRANSMISSION_PASSWORD}}
    - Romm:
        icon: romm.svg
        description: roms
        href: "https://roms.local.martinbjeldbak.com"
        server: localdocker
        container: romm
        widget:
            type: romm 
            url: http://romm:8080
            username: {{HOMEPAGE_VAR_ROMM_USERNAME}}
            password: {{HOMEPAGE_VAR_ROMM_PASSWORD}}

- Releases:
    - Calendar:
        description: tv and movie releases
        widget:
            type: calendar
            integrations:
                - type: sonarr
                  service_group: Media
                  service_name: Sonarr
                - type: radarr
                  service_group: Media
                  service_name: Radarr

- Applications:
    - Paperless-ngx:
        icon: paperless-ngx.svg
        href: "https://paperless.local.martinbjeldbak.com"
        description: document storage
        server: localdocker
        container: paperless
        widget:
            type: paperlessngx
            url: http://paperless:8000
            key: {{HOMEPAGE_VAR_PAPERLESS_KEY}}
    - Watchtower:
        icon: watchtower.svg
        description: docker updates
        server: localdocker
        container: watchtower
        widget:
            type: watchtower
            url: http://watchtower:8080
            key: {{HOMEPAGE_VAR_WATCHTOWER_API_TOKEN}}
    - Peanut Eaton 5E 1100i:
        icon: peanut.svg
        href: "https://peanut-eaton-5e-1100i.local.martinbjeldbak.com"
        description: ups monitoring
        server: localdocker
        container: peanut-eaton-5e-1100i
        widget:
            type: peanut
            url: http://peanut-eaton-5e-1100i:8080
            key: ups
    - Scrutiny:
        icon: scrutiny.svg
        href: "https://scrutiny.local.martinbjeldbak.com"
        description: s.m.a.r.t. tools
        server: localdocker
        container: scrutiny-web
        widget:
            type: scrutiny
            url: http://scrutiny-web:8080
    - Speedtest Tracker:
        icon: "https://speedtest.local.martinbjeldbak.com/img/speedtest-tracker-icon.png"
        href: "https://speedtest.local.martinbjeldbak.com"
        server: localdocker
        container: speedtest-tracker
        widget:
            type: speedtest
            url: http://speedtest-tracker
    - icloudpd:
        icon: docker.svg
        description: icloud photos downloader for backup to NAS
        server: localdocker
        container: icloudpd-n

- AdGuard:
    - AdGuard Home:
        icon: adguard-home.svg
        href: "https://dns.local.martinbjeldbak.com"
        description: main dns
        ping: dns.local.martinbjeldbak.com
        widget:
            type: adguard
            url: "https://dns.local.martinbjeldbak.com"
            username: {{HOMEPAGE_VAR_ADGUARD_HOME_ORIGIN_USERNAME}}
            password: {{HOMEPAGE_VAR_ADGUARD_HOME_ORIGIN_PASSWORD}}
    - AdGuard Home Replica:
        icon: adguard-home.svg
        href: "https://dns2.local.martinbjeldbak.com"
        description: secondary dns
        server: localdocker
        container: adguardhome
        widget:
            type: adguard
            url: http://adguardhome:3000
            username: {{HOMEPAGE_VAR_ADGUARD_HOME_REPLICA_USERNAME}}
            password: {{HOMEPAGE_VAR_ADGUARD_HOME_REPLICA_PASSWORD}}

- Home Automation:
    - Home Assistant:
        icon: home-assistant.svg
        href: "https://homeassistant.local.martinbjeldbak.com"
        description: homeassistant
        server: localdocker
        container: homeassistant
        widget:
            type: homeassistant
            url: http://homeassistant:8123
            key: {{HOMEPAGE_VAR_HOMEASSISTANT_ACCESS_TOKEN}}
    - Scrypted:
        icon: https://www.scrypted.app/images/web_hi_res_512.png
        href: "https://scrypted.local.martinbjeldbak.com"
        description: cameras
        server: localdocker
        container: scrypted
    - ESPHome:
        icon: esphome.svg
        href: "https://esphome.local.martinbjeldbak.com"
        description: esp32 configuration
        server: localdocker
        container: esphome
        widget:
            type: esphome
            url: http://esphome:6052


- Network:
    - OPNSense:
        icon: opnsense.svg
        description: firewall and router
        href: https://opnsense.local.martinbjeldbak.com/
        ping: 192.168.1.1
        widget:
            type: opnsense
            url: https://192.168.1.1
            username: {{HOMEPAGE_VAR_OPNSENSE_HOMEPAGE_USERNAME}}
            password: {{HOMEPAGE_VAR_OPNSENSE_HOMEPAGE_PASSWORD}}
    - Crowdsec:
        icon: crowdsec.svg
        description: ids/ips
        ping: 192.168.1.1
        widget:
            type: crowdsec
            url: http://192.168.1.1:8089
            username: {{HOMEPAGE_VAR_CROWDSEC_USERNAME}}
            password: {{HOMEPAGE_VAR_CROWDSEC_PASSWORD}}
    - Unifi:
        icon: unifi.svg
        description: network infra
        href: "https://unifi.local.martinbjeldbak.com"
        ping: unifi.local.martinbjeldbak.com
        widget:
            type: unifi
            url: https://unifi.local.martinbjeldbak.com
            username: {{HOMEPAGE_VAR_UNIFI_USERNAME}}
            password: {{HOMEPAGE_VAR_UNIFI_PASSWORD}}
    - Caddy:
        icon: caddy.png
        description: web server
        server: localdocker
        container: caddy
        widget:
            type: caddy
            url: http://caddy:2019
    - Gluetun:
        icon: gluetun.svg
        description: vpn
        server: localdocker
        container: gluetun
        widget:
            type: gluetun
            url: http://gluetun:8000
    - Tailscale Alderaan:
        icon: tailscale.svg
        description: mesh network
        href: "https://login.tailscale.com"
        widget:
            type: tailscale
            deviceid: {{HOMEPAGE_VAR_TAILSCALE_DEVICE_ID}}
            key: {{HOMEPAGE_VAR_TAILSCALE_API_KEY}}
    - Uptime Robot Home Internet:
        icon: "https://uptimerobot.com/assets/ico/favicon.ico"
        description: uptime monitoring
        href: "https://dashboard.uptimerobot.com/monitors/796218287"
        widget:
            type: uptimerobot
            url: https://api.uptimerobot.com
            key: {{HOMEPAGE_VAR_UPTIME_ROBOT_HOME_INTERNET_API_KEY}}
