---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: [duckduckgo, google]
    target: _blank

- openweathermap:
    label: Melbourne
    latitude: -37.8145996894535
    longitude: 144.94083240519333
    units: metric
    provider: openweathermap
    cache: 5
    format:
        maximumFractionDigits: 1

- datetime:
    text_size: xl
    locale: da
    format:
        timeStyle: short
        hourCycle: h23