---
name: Lint

on:
  push:
  schedule:
    - cron: "0 9 * * *" # every day at 9am

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ANSIBLE: false # see currently open issue https://github.com/github/super-linter/issues/1671

  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create dummy .env file
        run: cp .env.example .env

      - name: Run ansible lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: 'playbook.yml'