---
name: Lint

on:
  push:
  schedule:
    - cron: "0 9 * * *" # every day at 9am

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  homeassistant-config:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: homeassistant

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install homeassistant

      - name: Copy secrets
        run: mv secrets.sample.yaml secrets.yaml

      - name: Check configuration
        run: hass -c . --script check_config
