---
name: Lint

on:
  push:
  schedule:
    - cron: "0 9 * * *" # every day at 9am

jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ANSIBLE: false # see currently open issue https://github.com/github/super-linter/issues/1671
          FILTER_REGEX_EXCLUDE: 'adguardhome/AdGuardHome.tpl.yaml'

  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run ansible lint
        uses: ansible/ansible-lint-action@master
        with:
          targets: 'playbook.yml'

  homeassistant-config:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: homeassistant

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install homeassistant

      - name: Copy secrets
        run: mv secrets.sample.yaml secrets.yaml

      - name: Check configuration
        run: hass -c . --script check_config
